### ISSUE TITLE
experiment_id

### ISSUE THREAD

**Issue by mgxd** [INCF/BIDS2NDA#2]
Required when scantype is fMRI.
Since this is unique for each task, could be an optional key 'NDA_taskid' in *tasks.tsv / *bold.json. Add flag in parser? Manually add in after generated image03? WDYT?

**Comment by chrisfilo** [comment]
This should map to an existing experiment definition in NDA database what needs to be created by NDA tools (and verified by their curators). However, I noticed that if you completely omit the experiment_id column from image03 the validator only gives you a warning. Since BIDS2NDA saves the events files all of the timing information will still be saved (and truth to be told represented more accurately than current specification of experiments in NDA).

**Comment by mgxd** [comment]
validator is now throwing an error for this :(

**Comment by chrisfilo** [comment]
You mean an error about missing `experiment_id`? Did they add some way to programmatically query and add new experiments?
